source 'https://rubygems.org'
source "https://rubygems.org"

ruby gem 'install'

gem "sinatra"

group :development do
  gem "pry"
  gem "tux"
end
# Specify your gem's dependencies in install.gemspec
gemspec
